/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* RUBY_DTRACE_METHOD_ENTRY ( const char * classname, const char * methodname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_METHOD_ENTRY_ENABLED() __builtin_expect (method__entry_semaphore, 0)
#define ruby_method__entry_semaphore method__entry_semaphore
#else
#define RUBY_DTRACE_METHOD_ENTRY_ENABLED() __builtin_expect (ruby_method__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_method__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_METHOD_ENTRY(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, method__entry, arg1, arg2, arg3, arg4)

/* RUBY_DTRACE_METHOD_RETURN ( const char * classname, const char * methodname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_METHOD_RETURN_ENABLED() __builtin_expect (method__return_semaphore, 0)
#define ruby_method__return_semaphore method__return_semaphore
#else
#define RUBY_DTRACE_METHOD_RETURN_ENABLED() __builtin_expect (ruby_method__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_method__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_METHOD_RETURN(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, method__return, arg1, arg2, arg3, arg4)

/* RUBY_DTRACE_CMETHOD_ENTRY ( const char * classname, const char * methodname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_CMETHOD_ENTRY_ENABLED() __builtin_expect (cmethod__entry_semaphore, 0)
#define ruby_cmethod__entry_semaphore cmethod__entry_semaphore
#else
#define RUBY_DTRACE_CMETHOD_ENTRY_ENABLED() __builtin_expect (ruby_cmethod__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_cmethod__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_CMETHOD_ENTRY(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, cmethod__entry, arg1, arg2, arg3, arg4)

/* RUBY_DTRACE_CMETHOD_RETURN ( const char * classname, const char * methodname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_CMETHOD_RETURN_ENABLED() __builtin_expect (cmethod__return_semaphore, 0)
#define ruby_cmethod__return_semaphore cmethod__return_semaphore
#else
#define RUBY_DTRACE_CMETHOD_RETURN_ENABLED() __builtin_expect (ruby_cmethod__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_cmethod__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_CMETHOD_RETURN(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, cmethod__return, arg1, arg2, arg3, arg4)

/* RUBY_DTRACE_REQUIRE_ENTRY ( const char * rquiredfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_REQUIRE_ENTRY_ENABLED() __builtin_expect (require__entry_semaphore, 0)
#define ruby_require__entry_semaphore require__entry_semaphore
#else
#define RUBY_DTRACE_REQUIRE_ENTRY_ENABLED() __builtin_expect (ruby_require__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_require__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_REQUIRE_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, require__entry, arg1, arg2, arg3)

/* RUBY_DTRACE_REQUIRE_RETURN ( const char * requiredfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_REQUIRE_RETURN_ENABLED() __builtin_expect (require__return_semaphore, 0)
#define ruby_require__return_semaphore require__return_semaphore
#else
#define RUBY_DTRACE_REQUIRE_RETURN_ENABLED() __builtin_expect (ruby_require__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_require__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_REQUIRE_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, require__return, arg1, arg2, arg3)

/* RUBY_DTRACE_FIND_REQUIRE_ENTRY ( const char * requiredfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_FIND_REQUIRE_ENTRY_ENABLED() __builtin_expect (find__require__entry_semaphore, 0)
#define ruby_find__require__entry_semaphore find__require__entry_semaphore
#else
#define RUBY_DTRACE_FIND_REQUIRE_ENTRY_ENABLED() __builtin_expect (ruby_find__require__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_find__require__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_FIND_REQUIRE_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, find__require__entry, arg1, arg2, arg3)

/* RUBY_DTRACE_FIND_REQUIRE_RETURN ( const char * requiredfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_FIND_REQUIRE_RETURN_ENABLED() __builtin_expect (find__require__return_semaphore, 0)
#define ruby_find__require__return_semaphore find__require__return_semaphore
#else
#define RUBY_DTRACE_FIND_REQUIRE_RETURN_ENABLED() __builtin_expect (ruby_find__require__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_find__require__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_FIND_REQUIRE_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, find__require__return, arg1, arg2, arg3)

/* RUBY_DTRACE_LOAD_ENTRY ( const char * loadedfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_LOAD_ENTRY_ENABLED() __builtin_expect (load__entry_semaphore, 0)
#define ruby_load__entry_semaphore load__entry_semaphore
#else
#define RUBY_DTRACE_LOAD_ENTRY_ENABLED() __builtin_expect (ruby_load__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_load__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_LOAD_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, load__entry, arg1, arg2, arg3)

/* RUBY_DTRACE_LOAD_RETURN ( const char * loadedfile, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_LOAD_RETURN_ENABLED() __builtin_expect (load__return_semaphore, 0)
#define ruby_load__return_semaphore load__return_semaphore
#else
#define RUBY_DTRACE_LOAD_RETURN_ENABLED() __builtin_expect (ruby_load__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_load__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_LOAD_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, load__return, arg1, arg2, arg3)

/* RUBY_DTRACE_RAISE ( const char * classname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_RAISE_ENABLED() __builtin_expect (raise_semaphore, 0)
#define ruby_raise_semaphore raise_semaphore
#else
#define RUBY_DTRACE_RAISE_ENABLED() __builtin_expect (ruby_raise_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_raise_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_RAISE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, raise, arg1, arg2, arg3)

/* RUBY_DTRACE_OBJECT_CREATE ( const char * classname, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_OBJECT_CREATE_ENABLED() __builtin_expect (object__create_semaphore, 0)
#define ruby_object__create_semaphore object__create_semaphore
#else
#define RUBY_DTRACE_OBJECT_CREATE_ENABLED() __builtin_expect (ruby_object__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_object__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_OBJECT_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, object__create, arg1, arg2, arg3)

/* RUBY_DTRACE_ARRAY_CREATE ( long length, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_ARRAY_CREATE_ENABLED() __builtin_expect (array__create_semaphore, 0)
#define ruby_array__create_semaphore array__create_semaphore
#else
#define RUBY_DTRACE_ARRAY_CREATE_ENABLED() __builtin_expect (ruby_array__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_array__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_ARRAY_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, array__create, arg1, arg2, arg3)

/* RUBY_DTRACE_HASH_CREATE ( long length, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_HASH_CREATE_ENABLED() __builtin_expect (hash__create_semaphore, 0)
#define ruby_hash__create_semaphore hash__create_semaphore
#else
#define RUBY_DTRACE_HASH_CREATE_ENABLED() __builtin_expect (ruby_hash__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_hash__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_HASH_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, hash__create, arg1, arg2, arg3)

/* RUBY_DTRACE_STRING_CREATE ( long length, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_STRING_CREATE_ENABLED() __builtin_expect (string__create_semaphore, 0)
#define ruby_string__create_semaphore string__create_semaphore
#else
#define RUBY_DTRACE_STRING_CREATE_ENABLED() __builtin_expect (ruby_string__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_string__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_STRING_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, string__create, arg1, arg2, arg3)

/* RUBY_DTRACE_SYMBOL_CREATE ( const char * str, const char * filename, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_SYMBOL_CREATE_ENABLED() __builtin_expect (symbol__create_semaphore, 0)
#define ruby_symbol__create_semaphore symbol__create_semaphore
#else
#define RUBY_DTRACE_SYMBOL_CREATE_ENABLED() __builtin_expect (ruby_symbol__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_symbol__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_SYMBOL_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, symbol__create, arg1, arg2, arg3)

/* RUBY_DTRACE_PARSE_BEGIN ( const char * sourcefile, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_PARSE_BEGIN_ENABLED() __builtin_expect (parse__begin_semaphore, 0)
#define ruby_parse__begin_semaphore parse__begin_semaphore
#else
#define RUBY_DTRACE_PARSE_BEGIN_ENABLED() __builtin_expect (ruby_parse__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_parse__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_PARSE_BEGIN(arg1, arg2) \
DTRACE_PROBE2 (ruby, parse__begin, arg1, arg2)

/* RUBY_DTRACE_PARSE_END ( const char * sourcefile, int lineno ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_PARSE_END_ENABLED() __builtin_expect (parse__end_semaphore, 0)
#define ruby_parse__end_semaphore parse__end_semaphore
#else
#define RUBY_DTRACE_PARSE_END_ENABLED() __builtin_expect (ruby_parse__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_parse__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_PARSE_END(arg1, arg2) \
DTRACE_PROBE2 (ruby, parse__end, arg1, arg2)

/* RUBY_DTRACE_GC_MARK_BEGIN ( ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_GC_MARK_BEGIN_ENABLED() __builtin_expect (gc__mark__begin_semaphore, 0)
#define ruby_gc__mark__begin_semaphore gc__mark__begin_semaphore
#else
#define RUBY_DTRACE_GC_MARK_BEGIN_ENABLED() __builtin_expect (ruby_gc__mark__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__mark__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_GC_MARK_BEGIN() \
DTRACE_PROBE (ruby, gc__mark__begin)

/* RUBY_DTRACE_GC_MARK_END ( ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_GC_MARK_END_ENABLED() __builtin_expect (gc__mark__end_semaphore, 0)
#define ruby_gc__mark__end_semaphore gc__mark__end_semaphore
#else
#define RUBY_DTRACE_GC_MARK_END_ENABLED() __builtin_expect (ruby_gc__mark__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__mark__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_GC_MARK_END() \
DTRACE_PROBE (ruby, gc__mark__end)

/* RUBY_DTRACE_GC_SWEEP_BEGIN ( ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_GC_SWEEP_BEGIN_ENABLED() __builtin_expect (gc__sweep__begin_semaphore, 0)
#define ruby_gc__sweep__begin_semaphore gc__sweep__begin_semaphore
#else
#define RUBY_DTRACE_GC_SWEEP_BEGIN_ENABLED() __builtin_expect (ruby_gc__sweep__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__sweep__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_GC_SWEEP_BEGIN() \
DTRACE_PROBE (ruby, gc__sweep__begin)

/* RUBY_DTRACE_GC_SWEEP_END ( ) */
#if defined STAP_SDT_V1
#define RUBY_DTRACE_GC_SWEEP_END_ENABLED() __builtin_expect (gc__sweep__end_semaphore, 0)
#define ruby_gc__sweep__end_semaphore gc__sweep__end_semaphore
#else
#define RUBY_DTRACE_GC_SWEEP_END_ENABLED() __builtin_expect (ruby_gc__sweep__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__sweep__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_DTRACE_GC_SWEEP_END() \
DTRACE_PROBE (ruby, gc__sweep__end)

