#!/usr/bin/env bash

if
  [[ -s "/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment" ]]
then
  source "/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment'" >&2
  exit 1
fi
